  [31morigin/ControllerView/admin[m
  [31morigin/HEAD[m -> origin/master
  [31morigin/beneficiaries[m
  [31morigin/beneficiariesFile[m
  [31morigin/beneficiaryController[m
  [31morigin/develop[m
  [31morigin/entity/New[m
  [31morigin/entity/News[m
  [31morigin/event[m
  [31morigin/eventController[m
  [31morigin/eventViews[m
  [31morigin/feature/contactController[m
  [31morigin/feature/contactFormView[m
  [31morigin/feature/contactModel[m
  [31morigin/feature/contributorController[m
  [31morigin/feature/demo/final[m
  [31morigin/feature/eventController/method[m
  [31morigin/feature/loginAdmiController[m
  [31morigin/feature/loginController[m
  [31morigin/feature/metricModels[m
  [31morigin/feature/modelForeignKeys[m
  [31morigin/feature/organization-controller[m
  [31morigin/feature/organizations[m
  [31morigin/feature/potentialContributorController[m
  [31morigin/feature/programa-pass-controller[m
  [31morigin/feature/teamHTML[m
  [31morigin/feature/userController[m
  [31morigin/feature/usersServiceRefactor[m
  [31morigin/feature/voluntary-model[m
  [31morigin/feature_Model_Team[m
  [31morigin/feature_Potencial_Contributor[m
  [31morigin/fix/transaction-amount-data-type[m
  [31morigin/footer[m
  [31morigin/header[m
  [31morigin/homeController3[m
  [31morigin/homeView[m
  [31morigin/homecontroller[m
  [31morigin/master[m
  [31morigin/newsController[m
  [31morigin/programaPaas[m
  [31morigin/refactor/ModelsEntityControllerViews[m
  [31morigin/refactor/NewsEntity[m
  [31morigin/refactor/PotentialContributorToContributor[m
  [31morigin/refactor/contributorService[m
  [31morigin/refactor/controllerRequestResponse[m
  [31morigin/refactor/event[m
  [31morigin/saveImagesDBevent[m
  [31morigin/saveImagesDBteam[m
  [31morigin/teamType-implementation-html[m
  [31morigin/test1[m
  [31morigin/updateFragment[m
  [31morigin/updateHeader[m
  [31morigin/updateHome[m
  [31morigin/update_model_entity[m
